<?xml version="1.0"?>
<!-- m1n6_2 refers to mico v1 6DOF non-spherical 2fingers -->


<robot xmlns:xi="http://www.w3.org/2001/XInclude"
	xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
	xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
	xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
	xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
	xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
	xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
	xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
	xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
	xmlns:renderable="http://playerstage.sourceforge.net/gazebo/xmlschema/#renderable"
	xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
	xmlns:xacro="http://ros.org/wiki/xacro" name="m1n6s200">


  <xacro:include filename="$(find kinova_description)/urdf/m1n6s200.xacro"/>

  <link name="root">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size = "0.01 0.01 0.01"/>
      </geometry>
    <!--<material name="Black" /> -->
    </visual>

    <!--collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size = "0.01 0.01 0.01"/>
      </geometry>
    </collision-->
  </link>

  <!-- for gazebo -->
  <link name="world"/>

  <joint name="connect_root_and_world" type="fixed">
    <child link="root" />
    <parent link="world" />
    <origin xyz="0 0 0" rpy="0 0 0" />
  </joint>

  <xacro:property name="robot_root" value="root" />

  <xacro:m1n6s200  base_parent="${robot_root}"/>
  
  
<xacro:macro name="make_box" params="name x y z mass length width height" >
  <link name="${name}" >
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <inertial>
          <mass value="${mass}"/>
          <origin xyz="${x} ${y} ${z}"/>
          <inertia ixx="${0.0833333 * mass * (height**2 + length**2)}" ixy="0.0" ixz="0.0"
          iyy="${0.0833333 * mass * (width**2 + length**2)}" iyz="0.0"
          izz="${0.0833333 * mass * (width**2 + height**2)}" />
      </inertial>
    <visual name="visual">
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
          <box size="${length} ${width} ${height}" />
        </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length + 0.09} ${width + 0.09}  ${height + 0.09}" />
        </geometry>
    </collision>
  </link>
</xacro:macro>

<xacro:make_box name="camera_link" mass="0.01" length="0.035" width="0.18" height="0.025" x="0" y="0" z="0" />
  
  <!-- Gazebo color plugin for xtion -->
<gazebo reference="camera_link">
	<selfCollide>false</selfCollide>
	<static>true</static>
	<turnGravityOff>false</turnGravityOff>
	<sensor type="depth" name="camera">
		<pose>0 0 0 0 0 0</pose>
		<always_on>1</always_on>
		<visualize>true</visualize>
		<camera>
			<horizontal_fov>1.047</horizontal_fov>
			<image>
				<width>640</width>
				<height>480</height>
				<format>R8G8B8</format>
			</image>
			<depth_camera></depth_camera>
			<clip>
				<near>0.1</near>
				<far>100</far>
			</clip>
		</camera>
		<plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
			<alwaysOn>true</alwaysOn>
			<updateRate>30.0</updateRate>
			<cameraName>camera</cameraName>
			<frameName>camera_rgb_optical_link</frameName>
			<imageTopicName>rgb/image_raw</imageTopicName>
			<depthImageTopicName>depth_registered/image_raw</depthImageTopicName>
			<pointCloudTopicName>depth_registered/points</pointCloudTopicName>
			<cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
			<depthImageCameraInfoTopicName>depth_registered/camera_info</depthImageCameraInfoTopicName>
			<pointCloudCutoff>0.0</pointCloudCutoff>
			<pointCloudCutoffMax>4.5</pointCloudCutoffMax>
			<hackBaseline>0.07</hackBaseline>
			<distortionK1>0.0</distortionK1>
			<distortionK2>0.0</distortionK2>
			<distortionK3>0.0</distortionK3>
			<distortionT1>0.0</distortionT1>
			<distortionT2>0.0</distortionT2>
			<CxPrime>0.0</CxPrime>
			<Cx>0.0</Cx>
			<Cy>0.0</Cy>
			<focalLength>0.0</focalLength>
		</plugin>
	</sensor>
</gazebo>

<joint name="root_to_camera" type="fixed"> <!-- Connection between top bar and front -->
	<origin rpy=" ${0} ${pi/4} ${0}" xyz="-0.35 0.35 0.50"/> <!-- <origin rpy=" ${-M_PI/2 + 0.06} -0.04 ${-M_PI/2 - 0.05}" xyz="0.06 -0.02 -0.07"/> -->
	<child link="camera_link"/>
	<parent link="world"/>
</joint>

<link name="camera_rgb_optical_link"/>

<joint name="camera_to_rgb_optical" type="fixed"> <!-- Connection between top bar and front -->
	<origin rpy="${-pi/2} 0 ${-pi/2}" xyz="0.00 -0.0 0.00"/>
	<parent link="camera_link"/>
	<child link="camera_rgb_optical_link"/>
</joint>

</robot>
